agent_name: my_thermometer_aea
author: fetchai
version: 0.1.0
description: 'An AEA to represent a thermometer and sell temperature data.'
license: Apache-2.0
aea_version: 0.3.1
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/oef:0.2.0
- fetchai/stub:0.2.0
contracts: []
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/oef_search:0.1.0
skills:
- fetchai/error:0.2.0
- fetchai/thermometer:0.1.0
default_connection: fetchai/oef:0.2.0
default_ledger: fetchai
ledger_apis:
  fetchai:
    network: testnet
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
