agent_name: my_first_aea
author: fetchai
version: 0.21.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=0.11.0, <0.12.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.18.0
contracts: []
protocols:
- fetchai/default:0.13.0
- fetchai/signing:0.11.0
- fetchai/state_update:0.11.0
skills:
- fetchai/echo:0.15.0
default_connection: fetchai/stub:0.18.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing: {}
connection_private_key_paths: {}
dependencies: {}
