agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiftiqiqpxn7ghrurhepquzqzk3su3x6wanlnolt2uj772fzgz574m
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeihby6suvjc4kiw7wwm6ul6wggcvrj3sizars6le4rerqdgetuzdvu
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeibvtmpfzlig3ngtz6x2omc2rlx5knltnunbmg37tih5wlxnrfszvm
- fetchai/state_update:1.0.0:bafybeihaknve6slfpsml5bz62xqwxcpv3u7bqaskuataehsrgygoeiucqe
- open_aea/signing:1.0.0:bafybeighvx4vpsyspffggewidvkfq3lqbse6ap4tdewd6j5bs73ifnuaui
skills:
- fetchai/echo:0.19.0:bafybeiapq3npfk62s36rdnfd2is5kgmz6jw4nyoiggj3t4pslab2cazczq
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
