agent_name: my_first_aea
author: fetchai
version: 0.28.4
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.2
contracts: []
protocols:
- fetchai/default:1.1.6
- fetchai/signing:1.1.6
- fetchai/state_update:1.1.6
skills:
- fetchai/echo:0.20.5
default_connection: fetchai/stub:0.21.2
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
