agent_name: my_first_aea
author: fetchai
version: 0.2.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=0.3.0, <0.4.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.2.0
contracts: []
protocols:
- fetchai/default:0.1.0
skills:
- fetchai/echo:0.1.0
- fetchai/error:0.2.0
default_connection: fetchai/stub:0.2.0
default_ledger: fetchai
ledger_apis: {}
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
timeout: null
execution_timeout: null
max_reactions: null
