agent_name: my_first_aea
author: fetchai
version: 0.10.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=0.5.0, <0.6.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.9.0
contracts: []
protocols:
- fetchai/default:0.5.0
skills:
- fetchai/echo:0.6.0
- fetchai/error:0.5.0
default_connection: fetchai/stub:0.9.0
default_ledger: cosmos
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
