aea_version: 0.2.4
agent_name: my_first_aea
author: fetchai
connections:
- fetchai/stub:0.1.0
default_connection: fetchai/stub:0.1.0
default_ledger: fetchai
description: 'A simple agent to demo the echo skill.'
fingerprint: {}
ledger_apis: {}
license: Apache-2.0
logging_config:
  disable_existing_loggers: False
  version: 1
private_key_paths: {}
protocols:
- fetchai/default:0.1.0
registry_path: ../packages
skills:
- fetchai/echo:0.1.0
- fetchai/error:0.1.0
version: 0.1.0
