agent_name: aries_faber
author: fetchai
version: 0.7.0
description: An AEA representing Faber in the Aries demo.
license: Apache-2.0
aea_version: 0.5.2
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.6.0
- fetchai/p2p_libp2p:0.6.0
- fetchai/soef:0.5.0
- fetchai/stub:0.7.0
- fetchai/webhook:0.5.0
contracts: []
protocols:
- fetchai/default:0.4.0
- fetchai/http:0.4.0
- fetchai/oef_search:0.4.0
skills:
- fetchai/aries_faber:0.3.0
- fetchai/error:0.4.0
default_connection: fetchai/http_client:0.6.0
default_ledger: cosmos
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  cosmos: cosmos_private_key.txt
  ethereum: eth_private_key.txt
  fetchai: fet_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/oef_search:0.3.0: fetchai/soef:0.5.0
