agent_name: aries_faber
author: fetchai
version: 0.20.0
description: An AEA representing Faber in the Aries demo.
license: Apache-2.0
aea_version: '>=0.10.0, <0.11.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.17.0
- fetchai/p2p_libp2p:0.15.0
- fetchai/soef:0.16.0
- fetchai/webhook:0.13.0
contracts: []
protocols:
- fetchai/default:0.12.0
- fetchai/http:0.12.0
- fetchai/oef_search:0.13.0
- fetchai/signing:0.10.0
- fetchai/state_update:0.10.0
skills:
- fetchai/aries_faber:0.15.0
default_connection: fetchai/p2p_libp2p:0.15.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/http:0.12.0: fetchai/http_client:0.17.0
  fetchai/oef_search:0.13.0: fetchai/soef:0.16.0
connection_private_key_paths: {}
