agent_name: aries_faber
author: fetchai
version: 0.1.0
description: ''
license: Apache-2.0
aea_version: 0.3.1
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.2.0
- fetchai/oef:0.2.0
- fetchai/stub:0.2.0
- fetchai/webhook:0.1.0
contracts: []
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/http:0.1.0
- fetchai/oef_search:0.1.0
skills:
- fetchai/aries_faber:0.1.0
- fetchai/error:0.2.0
default_connection: fetchai/http_client:0.2.0
default_ledger: fetchai
ledger_apis: {}
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
