agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmNZkqQZByU5yn18ELka8TAyypiRxhHjAfMSdZfUy9mRwy
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:Qmaz96UaVyKeAJrCaEzr63KgkQZSL282J2EDiWsJRWuY64
contracts: []
protocols:
- fetchai/default:1.0.0:QmPbj4NogUssHakMCWpUPMB3byS7GT7HTXS9BwQRBtJu3s
- fetchai/gym:1.0.0:QmNgr5VRs1aggJ88w3B2rXb88gkCZmpNN89HpG3W4FoVRd
- fetchai/state_update:1.0.0:QmQMAE6WD9r84jXUDczdRn5w1Ufv4G6tC3LJKyGK9HG5WK
- open_aea/signing:1.0.0:QmWdCAiXpeT1tgrcf8uofKdQ6fLxMH77D5jwgQbbMo41df
skills:
- fetchai/gym:0.20.0:QmdQisuqLhq81NHuas9ALYgP1tw1cZoE3vGueREgG8PgCZ
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
