agent_name: gym_aea
author: fetchai
version: 0.19.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=0.11.0, <0.12.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.15.0
contracts: []
protocols:
- fetchai/default:0.13.0
- fetchai/gym:0.13.0
- fetchai/signing:0.11.0
- fetchai/state_update:0.11.0
skills:
- fetchai/gym:0.16.0
default_connection: fetchai/gym:0.15.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing: {}
connection_private_key_paths: {}
dependencies: {}
