name: prometheus
author: fetchai
version: 1.1.1
protocol_specification_id: fetchai/prometheus:1.0.0
type: protocol
description: A protocol for adding and updating metrics to a prometheus server.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmfEhyvVLVFFNbezUmDfNZajjdMoqVQRhxtAtgZzRpUr4y
  __init__.py: QmYijk3sMpZdj8fwsrEPfQvApP2Y1aVPEPkonyMnvrvqwb
  dialogues.py: QmVNNWsEzorKdYWxGSW1yUKd8PNXYjcRprtJijuuFSepkQ
  message.py: QmaDAqm5SqW9cFuBKB1CJiy9bHZGBTahTcudpWS7gwwMtb
  prometheus.proto: QmXMxMXbDH1LoFcV9QB7TvewUPu62poka43aKuujL73UN1
  prometheus_pb2.py: QmYqPhhZFgZfcAsXyD6Eef9tTqkXcgtcyUwVee4fFRoBvk
  serialization.py: QmYXXhfSkq4Xo93Yah4QhtriFpGZjr97sW8nozA6LpxzaQ
fingerprint_ignore_patterns: []
dependencies:
  protobuf: {}
