name: prometheus
author: fetchai
version: 0.3.0
type: connection
description: Connection for exposing agent metrics to prometheus server
license: Apache-2.0
aea_version: '>=0.10.0, <0.11.0'
fingerprint:
  README.md: QmZryaTzZ9MQnkXt6xLoPuQfHA2HzAkJUgUuqq6pfLWZ37
  __init__.py: QmWVrDiiePsr6vTnvbPTcDrayR89ji3hf25rs9V9TiJUPv
  connection.py: QmcCDNUWLCqvGQ7w9Xcz7HnbJtoBuEHKfAsCGk5rgJTbt2
fingerprint_ignore_patterns: []
connections: []
protocols: []
class_name: PrometheusConnection
config:
  host: 127.0.0.1
  port: 9090
excluded_protocols: []
restricted_to_protocols:
- fetchai/prometheus:0.3.0
dependencies:
  aioprometheus:
    version: <21.0.0,>=20.0.0
is_abstract: false
