agent_name: ml_model_trainer
author: fetchai
version: 0.25.0
description: An agent buying data and training a model from it.
license: Apache-2.0
aea_version: '>=1.0.0rc1, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.15.0
- fetchai/p2p_libp2p:0.18.0
- fetchai/soef:0.19.0
contracts: []
protocols:
- fetchai/default:0.13.0
- fetchai/ledger_api:0.11.0
- fetchai/ml_trade:0.13.0
- fetchai/oef_search:0.14.0
- fetchai/signing:0.11.0
- fetchai/state_update:0.11.0
skills:
- fetchai/generic_buyer:0.22.0
- fetchai/ml_train:0.23.0
default_connection: fetchai/p2p_libp2p:0.18.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing:
  fetchai/ledger_api:0.11.0: fetchai/ledger:0.15.0
  fetchai/oef_search:0.14.0: fetchai/soef:0.19.0
connection_private_key_paths: {}
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0rc1
