aea_version: 0.1.17
agent_name: ml_model_trainer
author: fetchai
connections:
- fetchai/oef:0.1.0
- fetchai/stub:0.1.0
default_connection: fetchai/stub:0.1.0
default_ledger: fetchai
description: 'An agent buying data and training a model from it.'
fingerprint: ''
ledger_apis: {}
license: Apache 2.0
logging_config:
  disable_existing_loggers: False
  version: 1
private_key_paths: []
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/ml_trade:0.1.0
- fetchai/oef:0.1.0
registry_path: ../packages
skills:
- fetchai/error:0.1.0
- fetchai/ml_train:0.1.0
version: 0.1.0
