agent_name: ml_model_trainer
author: fetchai
version: 0.11.0
description: An agent buying data and training a model from it.
license: Apache-2.0
aea_version: '>=0.5.0, <0.6.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.4.0
- fetchai/p2p_libp2p:0.8.0
- fetchai/soef:0.7.0
- fetchai/stub:0.9.0
contracts: []
protocols:
- fetchai/default:0.5.0
- fetchai/ledger_api:0.3.0
- fetchai/ml_trade:0.5.0
- fetchai/oef_search:0.5.0
skills:
- fetchai/error:0.5.0
- fetchai/generic_buyer:0.10.0
- fetchai/ml_train:0.10.0
default_connection: fetchai/p2p_libp2p:0.8.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/ledger_api:0.3.0: fetchai/ledger:0.4.0
  fetchai/oef_search:0.5.0: fetchai/soef:0.7.0
