agent_name: my_aea
author: default_author
version: 0.1.0
description: ''
license: Apache-2.0
aea_version: 0.3.3
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.4.0
contracts: []
protocols:
- fetchai/default:0.1.0
skills:
- fetchai/error:0.2.0
default_connection: fetchai/stub:0.4.0
default_ledger: fetchai
ledger_apis: {}
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  cosmos: cosmos_private_key.txt
  ethereum: eth_private_key.txt
  fetchai: fet_private_key.txt
registry_path: ../packages
