agent_name: tac_controller
author: fetchai
version: 0.17.0
description: An AEA to manage an instance of the TAC (trading agent competition)
license: Apache-2.0
aea_version: '>=0.9.0, <0.10.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.14.0
- fetchai/soef:0.15.0
contracts: []
protocols:
- fetchai/default:0.11.0
- fetchai/oef_search:0.12.0
- fetchai/signing:0.9.0
- fetchai/state_update:0.9.0
- fetchai/tac:0.12.0
skills:
- fetchai/error:0.11.0
- fetchai/tac_control:0.14.0
default_connection: fetchai/p2p_libp2p:0.14.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/oef_search:0.12.0: fetchai/soef:0.15.0
connection_private_key_paths: {}
