agent_name: thermometer_client
author: fetchai
version: 0.32.2
description: An AEA that purchases thermometer data.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.21.2
- fetchai/p2p_libp2p:0.27.2
- fetchai/soef:0.27.3
contracts: []
protocols:
- fetchai/default:1.1.3
- fetchai/fipa:1.1.3
- fetchai/ledger_api:1.1.3
- fetchai/oef_search:1.1.3
- fetchai/signing:1.1.3
- fetchai/state_update:1.1.3
skills:
- fetchai/generic_buyer:0.27.3
- fetchai/thermometer_client:0.26.3
default_connection: fetchai/p2p_libp2p:0.27.2
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing:
  fetchai/ledger_api:1.1.3: fetchai/ledger:0.21.2
  fetchai/oef_search:1.1.3: fetchai/soef:0.27.3
connection_private_key_paths: {}
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
