agent_name: thermometer_client
author: fetchai
version: 0.7.0
description: An AEA that purchases thermometer data.
license: Apache-2.0
aea_version: '>=0.5.0, <0.6.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.2.0
- fetchai/p2p_libp2p:0.6.0
- fetchai/soef:0.5.0
- fetchai/stub:0.6.0
contracts: []
protocols:
- fetchai/default:0.3.0
- fetchai/fipa:0.4.0
- fetchai/ledger_api:0.1.0
- fetchai/oef_search:0.3.0
skills:
- fetchai/error:0.3.0
- fetchai/generic_buyer:0.7.0
- fetchai/thermometer_client:0.6.0
default_connection: fetchai/p2p_libp2p:0.6.0
default_ledger: cosmos
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/ledger_api:0.1.0: fetchai/ledger:0.2.0
  fetchai/oef_search:0.3.0: fetchai/soef:0.5.0
