agent_name: my_first_aea
author: open_aea
version: 0.1.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeiftiqiqpxn7ghrurhepquzqzk3su3x6wanlnolt2uj772fzgz574m
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeihby6suvjc4kiw7wwm6ul6wggcvrj3sizars6le4rerqdgetuzdvu
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeic72ebyh7j4sqfa4fltvf7hm5taq2gtb43rnko3recmbr4b4vzcny
- fetchai/state_update:1.0.0:bafybeiaszshe2raobqmvayhxhwwzm5svvfgvdilr2hitdykg5k4mysekyy
- open_aea/signing:1.0.0:bafybeigf4hdi4yiiieaafftztcmommbxdzslpsvwm6trmvlizipcr7b6bm
skills:
- fetchai/echo:0.19.0:bafybeigxdesrwwkytn7kjm2hf3ksanozwbvlvafrkkf62cdovlmbt2txdu
default_connection: fetchai/stub:0.21.0
default_ledger: ethereum
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
