agent_name: random_beacon_feed
author: fetchai
version: 0.2.0
license: Apache-2.0
description: ''
aea_version: '>=0.10.0, <0.11.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.17.0
contracts: []
protocols:
- fetchai/default:0.12.0
- fetchai/http:0.12.0
- fetchai/signing:0.10.0
- fetchai/state_update:0.10.0
skills:
- fetchai/fetch_beacon:0.4.0
default_connection: fetchai/http_client:0.17.0
default_ledger: fetchai
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
registry_path: ../packages
