agent_name: random_beacon_feed
author: fetchai
version: 0.7.0
license: Apache-2.0
description: An agent that retrieves the Fetch.ai decentralised random beacon value.
aea_version: '>=1.0.0rc1, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/ledger:0.16.0
contracts: []
protocols:
- fetchai/default:0.14.0
- fetchai/ledger_api:0.12.0
- fetchai/signing:0.12.0
- fetchai/state_update:0.12.0
skills:
- fetchai/fetch_beacon:0.9.0
default_connection: fetchai/ledger:0.16.0
default_ledger: fetchai
required_ledgers:
- fetchai
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0rc3
---
public_id: fetchai/ledger:0.16.0
type: connection
config:
  ledger_apis:
    fetchai:
      address: https://rest-beaconworld.fetch.ai:443
      denom: atestfet
      chain_id: beaconworld-1
