aea_version: 0.1.5
agent_name: my_agent
authors: ''
connections:
- oef
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
registry_path: ../packages
skills:
- error
- test
url: ''
version: v1
