agent_name: car_data_buyer
author: fetchai
version: 0.5.0
description: An agent which searches for an instance of a `car_detector` agent and
  attempts to purchase car park data from it.
license: Apache-2.0
aea_version: '>=0.3.0, <0.4.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/oef:0.4.0
- fetchai/stub:0.5.0
contracts: []
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.2.0
- fetchai/oef_search:0.1.0
skills:
- fetchai/carpark_client:0.3.0
- fetchai/error:0.2.0
default_connection: fetchai/oef:0.4.0
default_ledger: fetchai
ledger_apis:
  fetchai:
    network: testnet
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
