agent_name: simple_service_registration
author: fetchai
version: 0.26.0
description: A simple example of service registration.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.20.0
- fetchai/soef:0.21.0
contracts: []
protocols:
- fetchai/default:0.15.0
- fetchai/fipa:0.16.0
- fetchai/oef_search:0.16.0
- fetchai/signing:0.13.0
- fetchai/state_update:0.13.0
skills:
- fetchai/simple_service_registration:0.19.0
default_connection: fetchai/p2p_libp2p:0.20.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing:
  fetchai/oef_search:0.16.0: fetchai/soef:0.21.0
connection_private_key_paths: {}
dependencies:
  aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
