agent_name: simple_service_registration
author: fetchai
version: 0.18.0
description: A simple example of service registration.
license: Apache-2.0
aea_version: '>=0.8.0, <0.9.0'
fingerprint: ''
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.13.0
- fetchai/soef:0.14.0
contracts: []
protocols:
- fetchai/default:0.10.0
- fetchai/fipa:0.11.0
- fetchai/oef_search:0.11.0
- fetchai/signing:0.8.0
- fetchai/state_update:0.8.0
skills:
- fetchai/error:0.10.0
- fetchai/simple_service_registration:0.14.0
default_connection: fetchai/p2p_libp2p:0.13.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
default_routing:
  fetchai/oef_search:0.11.0: fetchai/soef:0.14.0
connection_private_key_paths: {}
